In [1]:
import _init_paths
import caffe
import numpy as np
import os.path as osp

In [2]:
caffe.set_random_seed(13397)

In [3]:
print osp.abspath(_init_paths.root_dir)

/home/abhijit/Workspace/RenderAndCompare


In [4]:
net = caffe.Net('SoftmaxWithTemperature.prototxt', caffe.TEST)

---------- SoftMaxWithTemperature Layer Config ---------------
Temperature = Fixed (1.0)
bottom[0].shape =   (5, 3)
top[0].shape =      (5, 3)
--------------------------------------------------------------
---------- SoftMaxWithTemperature Layer Config ---------------
Temperature = bottom[1] with shape (5,)
bottom[0].shape =   (5, 4)
top[0].shape =      (5, 4)
--------------------------------------------------------------


In [5]:
net.blobs['data'].data[...] = np.array([[0, 200, 10], [0, 10, 200], [200, 200, 200], [-1, 0, 1], [1, 1, 0]])
net.blobs['temperature'].data[...] = np.array([1.0, 1.0, 100, 1e5, 1e14])

In [6]:
output = net.forward()


In [7]:
print output['softmax_prob_fixedT']

[[ 0.          1.          0.        ]
 [ 0.          0.          1.        ]
 [ 0.33333334  0.33333334  0.33333334]
 [ 0.09003057  0.24472848  0.66524094]
 [ 0.42231882  0.42231882  0.15536241]]


In [8]:
print output['softmax_prob2']

[[ 0.02033097  0.33155349  0.19676925  0.45134637]
 [ 0.00891814  0.01068074  0.91332608  0.06707503]
 [ 0.24704896  0.24647622  0.25414819  0.25232661]
 [ 0.24999996  0.25        0.25000006  0.25000003]
 [ 0.25        0.25        0.25        0.25      ]]
