In [1]:
import _init_paths
import caffe
import numpy as np
import os.path as osp

In [2]:
net = caffe.Net('test_viwpoint_expecation_layer.prototxt', caffe.TRAIN)

----------- ViewpointExpectation Layer Config ----------------
Number of bins = 24
bottom.shape =   (10, 24)
top[0].shape =   (10, 2)
--------------------------------------------------------------


In [3]:
diffs =[]
outputs = []
datas = []

In [17]:
data = np.zeros((10, 24))
data[:, 0] = 0.51
data[:, 23] = 0.49
datas.append(data.copy())
print data

[[ 0.51  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.49]
 [ 0.51  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.49]
 [ 0.51  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.49]
 [ 0.51  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.49]
 [ 0.51  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.49]
 [ 0.51  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.49]
 [ 0.51  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.    0.    0.    0.    0.    0.    0

In [18]:
net.blobs['data'].data[...] = data
output = net.forward()
outputs.append(output['veiw_normalized_cs'].copy())

In [19]:
cs = output['veiw_normalized_cs']

In [20]:
np.arctan2(cs[:,1], cs[:,0]) * 180 / np.pi

array([ 0.15086216,  0.15086216,  0.15086216,  0.15086216,  0.15086216,
        0.15086216,  0.15086216,  0.15086216,  0.15086216,  0.15086216], dtype=float32)

In [21]:
# net.blobs['veiw_normalized_cs'].diff

In [22]:
inp = net.backward()

In [23]:
diffs.append(net.blobs['data'].diff.copy())

In [24]:
print len(diffs), len(outputs), len(datas)


2 2 2


In [38]:
outputs[1] - outputs[0]

array([[ -3.45706940e-06,   2.63303821e-03],
       [ -3.45706940e-06,   2.63303821e-03],
       [ -3.45706940e-06,   2.63303821e-03],
       [ -3.45706940e-06,   2.63303821e-03],
       [ -3.45706940e-06,   2.63303821e-03],
       [ -3.45706940e-06,   2.63303821e-03],
       [ -3.45706940e-06,   2.63303821e-03],
       [ -3.45706940e-06,   2.63303821e-03],
       [ -3.45706940e-06,   2.63303821e-03],
       [ -3.45706940e-06,   2.63303821e-03]], dtype=float32)

In [40]:
np.linalg.norm(outputs[0], axis=1)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.], dtype=float32)

In [31]:
in_diff = datas[1] - datas[0]

In [32]:
in_diff

array([[ 0.01,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.01],
       [ 0.01,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.01],
       [ 0.01,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.01],
       [ 0.01,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.01],
       [ 0.01,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  , -0.01],
       [ 0.01,  0.  ,  0.  ,  0.  ,

In [ ]:
out_diff = outputs[1] - outputs[0]

In [ ]:
out_diff.shape

In [ ]:
inv_in_diff = 1/in_diff

In [ ]:
out_diff[0,0] / (in_diff[0,:] + 1e-12)

In [ ]:
diffs[0]